ERROR: Trying to update to 2.1.1
Taking this original project and updating to run with a vagrant file called riak-ruby-vagrant. The server starts now but search functionality fails. Previous CRDT and 2i implementations don't work on newer rev, so exploring that.